# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLFuTv5Y2SFi1NMSq_j33EYPOaB5r6CR
"""

#Goal of this program is to ask the user what they want to calculate and then return the performed math equation.
#I wasn't here for the assignment so I'm not sure the exact specifications it should be but I imagine this fufills the need

import math
ui = input("Hi! I'm you're calculator today. I can add, subtract, divide, mulitply, square root, modulus, and exponent! Enter a number from the menu of options: \n1: Add \n2: Subtract \n3: Divide \n4: Multiply \n5: Square Root \n6: Modulus \n7: Exponent\n")


def addnum():
  num1 = int(input("Great. What is the first number?"))
  num2 = int(input("Good. What is the second number?"))
  return num1+num2

def subnum():
  num1 = int(input("Great what is your first number."))
  num2 = int(input("What do you want to subtract from " + str(num1)))
  return num1-num2

def dividenum():
  num1 = int(input("Great what is the numerator?"))
  num2 = int(input("What do you want to divide " + str(num1) + " by?"))
  return num1/num2

def multiplynum():
  num1 = int(input("Great. What is the first number?"))
  num2 = int(input("Good. What is the second number?"))
  return num1*num2

def expnt():
  num1 = int(input("Great. What is the first number?"))
  num2 = int(input("To what power?"))
  return num1**num2

def sqroot():
  num1 = int(input("Great. What is the number you want to square root?"))
  return math.sqrt(num1)

def mod():
  num1 = int(input("Great. What is the first number?"))
  num2 = int(input("Good. What is the second number?"))
  return num1 % num2

ui = int(ui)

if ui==1:
  print(addnum())
elif ui==2:
  print(subnum())
elif ui==3:
  print(dividenum())
elif ui==4:
  print(multiplynum())
elif ui==5:
  print(sqroot())
elif ui==6:
  print(mod())
elif ui==7:
  print(expnt())
else:
  print("That is not an option. Restart.")