# -*- coding: utf-8 -*-
"""DepositwInterest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18oq7lwtRehVglNQ2SSKdc2ApRTdBUyNg
"""

name = input("Hi, please enter your name: ")
customer_type = input("Enter customer type (n for new, e for existing): ")
deposit = float(input("Enter deposit amount: "))

if customer_type == 'n':
  interest = float(0.03)
else:
  if deposit <= 1000:
    interest = float(0.03)
  elif deposit <= 10000:
    interest = float(0.0325)
  else:
    interest = float(0.035)

amount = (1 + interest) * deposit
print(f'{name}, you will have ${round(amount, 2)} in your account!')