# -*- coding: utf-8 -*-
"""LeapYear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWn5GjRGeU5R67v32b5pUgRtGJouoG-C
"""

year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(str(year) + " is a leap year!")
else:
    print(str(year) + " is not a leap year.")