# -*- coding: utf-8 -*-
"""Mortgage Class Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLc000X_MZRm3mS_3Ogf_GszUIzAqmYd
"""

class Mortgage:
  def __init__(self, amount, maturity, interest):
    self.amount = amount
    self.maturity = maturity
    self.interest = interest

  def getAmount(self):
    return self.amount
  def getMaturity(self):
    return self.maturity
  def getInterest(self):
    return self.interest
  def monthlyPayment(self):
    b = float(self.amount)
    n = float(self.maturity * 12)
    r = float(self.interest / 100)
    temp = float((1+r)**n)

    return b * (((r)*(temp)) / ((temp - 1)))

  def set_interest(self, newInterest):
    self.interest = newInterest

  def __str__(self):
    return f"Initial loan amount: ${self.amount} \nMaturity Term: {self.maturity} \nInterest Rate: {self.interest}"



m = Mortgage(1000000, 30, 6)
m.monthlyPayment()
print(m)

