# -*- coding: utf-8 -*-
"""PandasAssignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXKw5i2a6CeFLxjsYf5tQE03L_o9j8en

## Data Analysis assignment (20 points)

You have been given the dataset `travel-times` in a CSV format. This dataset comes from a driver that uses an app to track GPS coordinates as he drives to work and back each day. The app collects the location and elevation data. In total, data for about 200 trips are summarized in this data set.

Load the `travel-times` in a `df` variable using `pandas` and then perform the following:
- print the shape of the dataset **(1 points)**
- print the first 15 rows of the dataset **(1 points)**
- get information for the features (columns) with missing values **(1 points)**
- drop duplicate values (if any) by keeping only the last instance **(1 points)**
- calculate the total number of missing values (if any) on each column **(2 points)**
- create two copies of the dataframe, and then:
    - drop rows with missing values from the 1st copy **(1 points)**
    - drop columns with missing values from the 2nd copy **(1 points)**
- get summary statistics and see the correlation between the numerical columns **(1 points)**
- show rows 11 to 14 **(1 points)**
- create a subset with trips occurred on November 23, 2011 and January 6, 2012 **(2 points)**
- produce a scatterplot between `Distance` and `TotalTime` **(1 points)**
    * Use:
```python
import matplotlib.pyplot as plt
plt.rcParams.update({'font.size': 20, 'figure.figsize': (10, 8)})
```
- produce boxplots for `AvgSpeed` and `AvgMovingSpeed` (use different cells for each) **(2 points)**
"""

import matplotlib.pyplot as plt
import pandas as pd



df = pd.read_csv("travel-times.csv")
#print the shape of the dataset
print(df.shape)

#print the first 15 rows of the dataset
print(df.head(15))

#get information for the features (columns) with missing values
df.info()

#drop duplicate values (if any) by keeping only the last instance
df.drop_duplicates(inplace=True, keep='last')

#calculate the total number of missing values (if any) on each column
missing_val_count = df.isnull().sum()

#create two copies of the dataframe, and then
df_copy1 = df.copy()
df_copy2 = df.copy()
# drop rows with missing values from the 1st copy:
df_copy1.dropna(inplace=True)
# drop columns with missing values from the 2nd copy
df_copy2.dropna(inplace=True, axis=1)

# get summary statistics and see the correlation between the numerical columns
df.describe()
df_corr = df.select_dtypes(include=['number']) #It kept spitting errors out at me for the strings so this was my way of filtering it
df_corr = df_corr.corr()

# show rows 11 to 14
print(df.iloc[11:15])

#create a subset with trips occurred on November 23, 2011 and January 6, 2012
df['Date'] = pd.to_datetime(df['Date'], format="%m/%d/%Y")
newdf= df[(df['Date']>= '11/23/2011') & (df['Date']<= '1/6/2012')]

#produce a scatterplot between Distance and TotalTime
plt.rcParams.update({'font.size': 20, 'figure.figsize': (10, 8)})
df.plot(kind='scatter', x='Distance',y='TotalTime', title='Distance over Total Time')

#produce boxplots for AvgSpeed and AvgMovingSpeed (use different cells for each)
df.plot(kind='box', x='AvgSpeed', y='AvgMovingSpeed', title='Boxplot for Average Speed and Average Moving Speed')