# -*- coding: utf-8 -*-
"""ParkingGarage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18oq7lwtRehVglNQ2SSKdc2ApRTdBUyNg
"""

for hour in range(1,9):
  fee = 5 + 2.5*hour
  if fee < 10:
    fee = 10.0
  elif fee>20:
    fee = 20.0
  print (f'Your fee is {fee} for {hour} hours.')