# -*- coding: utf-8 -*-
"""Point Example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cOhevmRQq4pydDGQZKa4496TDFTib3uc
"""

class Point:
  def __init__(self, x, y):
    self.x = x
    self.y = y

  def distance(self, other):
    x_diff = (self.x - other.x) ** 2
    y_diff = (self.y - other.y) ** 2
    return (x_diff + y_diff) ** 0.5


class Point3D(Point):
  def __init__(self, x, y, z):
    super().__init__(x,y)
    self.z = z


p1= Point(3,4)
p2= Point(6,8)
print(p1.distance(p2))

