# -*- coding: utf-8 -*-
"""PopulatingADict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVp67eLS_74cUSsF-vqKxaJdLGQGq8Vy
"""

months = {}

numbers = [1,2,3,4,5,6,7,8,9,10,11,12]
names = ["January","Feburary","March","April","May","June","July","August","September","October","November","December"]

for i in range(len(numbers)):
  months[numbers[i]] = names[i]

print(months)