# -*- coding: utf-8 -*-
"""RockPaperScissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2II9LbOsOwftCKbunxjU_nmjFkkOxcx
"""

#Rock paper scissors mini-game using random function

import random

user_choice = input("Enter your choice (rock, paper, or scissors): ")
computer_choice = random.choice(["rock", "paper", "scissors"])

print("You chose: " + user_choice)
print("Computer chose: " + computer_choice)

if user_choice == computer_choice:
    print("It's a tie!")
elif ((user_choice == "rock" and computer_choice == "scissors") or (user_choice == "paper" and computer_choice == "rock") or (user_choice == "scissors" and computer_choice == "paper")):
    print("You win!")
else:
    print("Computer won :(")